# Generated by Django 5.2.11 on 2026-03-15 13:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('thika', 'Thika'), ('nyeri', 'Nyeri'), ('meru', 'Meru')], max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(default='254112284093', max_length=20)),
                ('working_hours', models.CharField(default='Mon-Sat: 8AM - 6PM, Sun: 10AM - 4PM', max_length=200)),
                ('google_maps_link', models.URLField(blank=True)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['-is_headquarters', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year_from', models.PositiveIntegerField()),
                ('year_to', models.PositiveIntegerField()),
                ('budget_ksh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preferred_source', models.CharField(choices=[('japan', 'Japan'), ('uae', 'UAE / Dubai'), ('uk', 'United Kingdom'), ('usa', 'USA'), ('germany', 'Germany'), ('south_africa', 'South Africa')], default='japan', max_length=20)),
                ('specifications', models.TextField(blank=True, help_text='Specific requirements, color, features, etc.')),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Import Order',
                'verbose_name_plural': 'Import Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position_applied', models.CharField(choices=[('sales_executive', 'Sales Executive'), ('mechanic', 'Mechanic / Technician'), ('driver', 'Driver'), ('admin', 'Administrative Staff'), ('marketing', 'Marketing'), ('finance', 'Finance & Accounts'), ('it', 'IT Support'), ('customer_service', 'Customer Service'), ('other', 'Other')], max_length=50)),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(upload_to='careers/cvs/%Y/%m/')),
                ('is_shortlisted', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=150)),
                ('seller_phone', models.CharField(max_length=20)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_location', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('asking_price_ksh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('foreign_used', 'Foreign Used'), ('local_used', 'Locally Used')], max_length=20)),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes by staff')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Submission',
                'verbose_name_plural': 'Commission Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commissions/images/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.commissionsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('inspection_type', models.CharField(choices=[('pre_purchase', 'Pre-Purchase Inspection'), ('roadworthy', 'Roadworthy Certificate'), ('valuation', 'Vehicle Valuation'), ('full_service', 'Full Service Inspection')], max_length=30)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.PositiveIntegerField()),
                ('preferred_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
            ],
            options={
                'verbose_name': 'Inspection Booking',
                'verbose_name_plural': 'Inspection Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('model', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('pickup', 'Pickup / Truck'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('minivan', 'Minivan / MPV'), ('wagon', 'Station Wagon'), ('sports', 'Sports Car'), ('electric', 'Electric Vehicle'), ('hybrid', 'Hybrid'), ('van', 'Van / Bus'), ('lorry', 'Lorry / Heavy Truck')], max_length=50)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2026)])),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('foreign_used', 'Foreign Used'), ('local_used', 'Locally Used')], default='foreign_used', max_length=20)),
                ('engine_cc', models.PositiveIntegerField(blank=True, help_text='Engine displacement in CC', null=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG')], default='petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'), ('semi_auto', 'Semi-Automatic')], default='automatic', max_length=20)),
                ('drive_type', models.CharField(choices=[('fwd', 'Front Wheel Drive'), ('rwd', 'Rear Wheel Drive'), ('awd', 'All Wheel Drive'), ('4wd', '4WD')], default='fwd', max_length=10)),
                ('mileage_km', models.PositiveIntegerField(blank=True, help_text='Mileage in KM', null=True)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('price_ksh', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=12)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('is_import', models.BooleanField(default=False, help_text='Import listing from Japan/UAE etc.')),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, help_text='Comma separated or JSON list of features')),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('pending', 'Pending Review'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_commission', models.BooleanField(default=False, help_text='Car submitted by public for commission sale')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.branch')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.brand')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_approved', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_purchased', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('preferred_contact', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Phone Call')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.vehicle')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.vehicle')),
            ],
            options={
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['slug'], name='core_vehicl_slug_6d9b54_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'model'], name='core_vehicl_brand_i_68959a_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['category'], name='core_vehicl_categor_5cc98c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['year'], name='core_vehicl_year_43064b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['price_ksh'], name='core_vehicl_price_k_4e2e62_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='core_vehicl_status_187554_idx'),
        ),
    ]
